language: python
python:
    - "2.7"
install: 
    - "pip install -r requirements.txt"
    - "pip install -r users/test/requirements.txt"
script:
    - "nosetests -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=users users"
    - "pylint --output-format=parseable --reports=y --rcfile=pylintrc users"
    - "pep8 --repeat --ignore W391 --exclude venv,none.py users"
