 CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  guid VARCHAR(37) NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  website TEXT,
  email_updates BOOL DEFAULT 0,
  date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
  latitude FLOAT,
  longitude FLOAT);
